### ISSUE TITLE
[GCE] Default DNS server

### ISSUE THREAD

**Issue by jonandernovella** [kubenow/KubeNow#122] opened 2017-03-20 17:02 UTC
By default, the containers use the public google DNS server to resolve host names, instead of the kube-dns server. This makes the containers unable to communicate.

**Comment by mcapuccini** [comment] 2017-03-21 11:00
@jonandernovella containers use the DNS of the network they are plugged into. If your container runs as host it will use the Google's DNS by default, unless you specified something else in the `terraform.tfvars` file. If your container is instead running in the overlay network, it will use kube-dns. I am closing this issue, as this is by design. Please feel free to open it again if this becomes blocking for you.

**Closed by mcapuccini** 2017-03-21 11:00 UTC
Labels: question
