### ISSUE TITLE
configuration filename mismatch in docs

### ISSUE THREAD

**Issue by ilveroluca** [kubenow/KubeNow#404] opened 2018-07-04 10:13 UTC
The current docs on how to perform a deployment on AWS reference a file `config.tfvars`, while it looks like `kn init` creates `terraform.tfvars`:

https://kubenow.readthedocs.io/en/stable/getting_started/bootstrap.html#deploy-on-amazon-web-services-aws

**Comment by andersla** [comment] 2018-07-04 11:09
Thanks @ilveroluca The documentation is a little bit out of sync there. It will be fixed as soon as we release a new stable version of KubeNow.

**Comment by andersla** [comment] 2018-07-04 11:14
`terraform.tfvars` has been changed to `config.tfvars` in later versions of KubeNow

**Comment by mcapuccini** [comment] 2018-07-23 08:00
Hi Luca, what version of the client are you using?

**Comment by ilveroluca** [comment] 2018-07-31 08:59
Sorry @mcapuccini but I don't remember.  I was following [the instructions for the PhenoMeNal plugin](https://github.com/phnmnl/KubeNow-plugin) but I couldn't tell you what version of the software I was using.

**Comment by mcapuccini** [comment] 2018-07-31 09:10
Alright, no worries. I thought we were talking about the [official documentation](http://kubenow.readthedocs.io/en/stable/getting_started/bootstrap.html#deploy-on-openstack) which seems to be in synch. I am leaving this open so we remember to fix the PhenoMeNal documentation as well.

**Comment by andersla** [comment] 2018-07-31 09:15
The Phenomenal documentation is in sync, the problem is that the PhenoMeNal branch of KubeNow contains features not yet available in the KubeNow master and therefore the documentation between PhenoMeNal and KubeNow master is not always matching.

**Comment by mcapuccini** [comment] 2018-07-31 09:16
Good 🙂 Closing then!

**Closed by mcapuccini** 2018-07-31 09:16 UTC
Labels: minor
